name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # Setup Python (para backend, se necessário)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies for building
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxss1 fakeroot dpkg

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      # Build frontend with Vite
      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Prepare app directory for electron-builder
      - name: Prepare app for packaging
        run: |
          cd frontend
          npm run prepack

      # Build AppImage and DEB using electron-builder
      - name: Build AppImage and DEB
        run: |
          cd frontend
          npx electron-builder --linux deb AppImage --publish never
        env:
          SKIP_NOTARIZATION: true

      # List generated files for debugging
      - name: List build artifacts
        run: |
          echo "=== Searching for build artifacts ==="
          find frontend -type f \( -name "*.AppImage" -o -name "*.deb" \) 2>/dev/null | head -20
          echo ""
          echo "=== Content of frontend directory ==="
          ls -lah frontend/ | grep -E "AppImage|deb" || echo "No AppImage or deb files in frontend/"
          echo ""
          echo "=== Content of frontend/dist ==="
          ls -lah frontend/dist/ 2>/dev/null | tail -20 || echo "frontend/dist not found"

      # Extract version from tag
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      # Create GitHub Release with assets
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: Release ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            frontend/dist/UClip-*.AppImage
            frontend/dist/UClip-*.deb
            frontend/UClip-*.AppImage
            frontend/UClip-*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload artifacts for inspection
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts-${{ steps.version.outputs.VERSION }}
          path: |
            frontend/dist/*.AppImage
            frontend/dist/*.deb
          retention-days: 30
